#include "lexer/lexer.h"

#include "parser.tab.h"

/* yylex is generated by flex; Bison's header declares yylval/yylloc. */
extern int yylex(void);

int lexer_next(Token *out)
{
    yylval = NULL;
    int kind = yylex();
    out->kind = kind;
    out->lexeme = yylval;
    out->span = yylloc;
    return kind;
}
